#!/usr/bin/env bash
# headless-signing-config — write ~/.gitconfig.local with overrides for
# git commit signing on a headless Mac.
#
# Why: the public gitconfig sets gpg.ssh.program to the laptop's
# /Applications/1Password.app/.../op-ssh-sign and user.signingkey to a
# literal pubkey value (resolved via the 1P SSH agent). On a headless box
# with no 1P GUI app, op-ssh-sign isn't usable and the agent socket
# doesn't exist — git falls through to ssh-keygen reading a key off disk
# and prompts for a passphrase.
#
# This script writes a ~/.gitconfig.local that points user.signingkey at
# the on-disk public key (placed by fetch-headless-ssh-key.sh, default
# ~/.ssh/id_ed25519.pub) and replaces gpg.ssh.program with the system
# ssh-keygen. The public dotfiles' gitconfig has an [include] for
# ~/.gitconfig.local at the end, so these overrides win on this box and
# are no-op on the laptop.
#
# After this runs, register the same pubkey on GitHub as a SIGNING key
# (separate from auth keys). From the laptop:
#   op --account jbctechsolutions.1password.com read \
#     "op://Local Dev/$(hostname -s)/public key" \
#     | gh api -X POST user/ssh_signing_keys \
#         -F title="$(hostname -s) (signing)" -F key=@/dev/stdin
#
# Idempotent. No-op if ~/.gitconfig.local already has matching values.
#
# Env overrides:
#   SSH_KEY_FILE   default: $HOME/.ssh/id_ed25519 (must match
#                  fetch-headless-ssh-key.sh)
#   GIT_LOCAL_CFG  default: $HOME/.gitconfig.local

set -euo pipefail

KEY_FILE="${SSH_KEY_FILE:-$HOME/.ssh/id_ed25519}"
PUB_FILE="${KEY_FILE}.pub"
LOCAL_CFG="${GIT_LOCAL_CFG:-$HOME/.gitconfig.local}"

log() { printf '[git-signing] %s\n' "$*" >&2; }

if [[ ! -s "$PUB_FILE" ]]; then
  log "no public key at $PUB_FILE; run fetch-headless-ssh-key.sh first"
  exit 0
fi

# Ssh-keygen the system one (not 1P's op-ssh-sign).
SSH_KEYGEN="$(command -v ssh-keygen || true)"
[[ -n "$SSH_KEYGEN" ]] || { log "error: ssh-keygen not on PATH"; exit 1; }

# Use ~ in the config (git expands it). PUB_FILE may be /Users/joel/...
# or ~/... depending on env; normalize to a tilde path for portability
# across home dirs.
PUB_TILDE="${PUB_FILE/#$HOME/~}"

# Idempotency: if file already has the right values, skip.
if [[ -f "$LOCAL_CFG" ]] \
   && grep -q "signingkey = $PUB_TILDE" "$LOCAL_CFG" \
   && grep -q "program = $SSH_KEYGEN"  "$LOCAL_CFG"; then
  log "already configured: $LOCAL_CFG points at $PUB_TILDE + ssh-keygen"
  exit 0
fi

umask 077
tmp="$(mktemp "${LOCAL_CFG}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

cat > "$tmp" <<EOF
# Host-local git overrides for $(hostname -s).
# Generated by ~/.dotfiles/tools/git/headless-signing-config.sh
# (headless dotbot profile). Edit the script, not this file.
[user]
    signingkey = $PUB_TILDE
[gpg "ssh"]
    program = $SSH_KEYGEN
[commit]
    gpgsign = true
EOF
chmod 600 "$tmp"
mv -f "$tmp" "$LOCAL_CFG"
trap - EXIT

log "wrote $LOCAL_CFG"
log "  signingkey = $PUB_TILDE"
log "  gpg.ssh.program = $SSH_KEYGEN"
log "next: register the public key on GitHub as a signing key (see script header)"
