#!/usr/bin/env bash
# claude-plugins.sh — pinned, dotfiles-tracked Claude Code plugin management.
#
# Subcommands:
#   status   Report drift (installed vs lockfile) and patch state. Non-zero on drift.
#   update   Update marketplaces/plugins to latest, regenerate lockfile, reapply
#            patches, relink hooks, and print a committable diff. Never auto-commits.
#   restore  Rebuild pinned state from the lockfile (install-then-patch), for a
#            fresh machine or drift repair.
#   gen-lock Regenerate the lockfile from current machine state (used by update).
#
# Pinning model (hybrid, per marketplace type — see docs/plans/2026-07-09-001):
#   git-backed marketplace  -> true pin: record + checkout marketplace commit SHA.
#   GCS official marketplace -> drift-assert: record version, install latest on
#                               restore, assert installed == locked, fail loud on drift.
#   Exact historical versions of GCS-official plugins cannot be reinstalled via the
#   Claude CLI (no --version flag, no git history); drift-assert is the honest ceiling.
#
# Patches (in-plugin edits) are strict git patches, applied fail-loud. Hooks are
# symlinked from apps/claude/hooks via dotbot; relink here is a safety net.

set -euo pipefail

# --- output helpers ----------------------------------------------------------
if [ -t 1 ]; then
  C_GREEN='\033[0;32m'; C_YELLOW='\033[1;33m'; C_RED='\033[0;31m'
  C_BLUE='\033[0;34m'; C_DIM='\033[2m'; C_NC='\033[0m'
else
  C_GREEN=''; C_YELLOW=''; C_RED=''; C_BLUE=''; C_DIM=''; C_NC=''
fi
info() { printf '%b\n' "${C_BLUE}•${C_NC} $*"; }
ok()   { printf '%b\n' "${C_GREEN}✓${C_NC} $*"; }
warn() { printf '%b\n' "${C_YELLOW}⚠${C_NC} $*" >&2; }
die()  { printf '%b\n' "${C_RED}✗${C_NC} $*" >&2; exit 1; }

# --- paths (env-overridable for tests; production defaults unchanged) --------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="${DOTFILES_ROOT:-$(cd "${SCRIPT_DIR}/../../.." && pwd)}"
LOCKFILE="${DOTFILES_ROOT}/apps/claude/plugins/plugins.lock.json"
PATCHES_DIR="${DOTFILES_ROOT}/apps/claude/patches"
HOOKS_SRC="${DOTFILES_ROOT}/apps/claude/hooks"
CLAUDE_HOME="${CLAUDE_HOME:-${HOME}/.claude}"
MARKETPLACES_DIR="${CLAUDE_HOME}/plugins/marketplaces"
SETTINGS_JSON="${CLAUDE_HOME}/settings.json"

# --- claude binary (interactive shells wrap it in a zsh function) ------------
claude_bin() {
  if [ -n "${CLAUDE_BIN:-}" ]; then
    echo "$CLAUDE_BIN"
  elif [ -x /opt/homebrew/bin/claude ]; then
    echo /opt/homebrew/bin/claude
  elif command -v claude >/dev/null 2>&1; then
    command -v claude
  else
    die "claude binary not found (looked at /opt/homebrew/bin/claude and PATH)"
  fi
}

# --- marketplace helpers -----------------------------------------------------
marketplace_is_git() { [ -d "${MARKETPLACES_DIR}/$1/.git" ]; }
marketplace_sha() {
  if marketplace_is_git "$1"; then
    git -C "${MARKETPLACES_DIR}/$1" rev-parse HEAD 2>/dev/null || echo ""
  else
    echo ""
  fi
}

# --- lockfile generation -----------------------------------------------------
# Emits a sorted lock of enabled user-scope plugins, keyed "plugin@marketplace",
# each { version, marketplace, marketplaceType, gitCommitSha, scope }.
gen_lock() {
  local list_json
  list_json="$("$(claude_bin)" plugin list --json 2>/dev/null)" \
    || die "could not read 'claude plugin list --json'"

  # Precompute marketplace sha map for git-backed marketplaces.
  local sha_map=""
  local mp
  for mp in "${MARKETPLACES_DIR}"/*/; do
    [ -d "$mp" ] || continue
    local name; name="$(basename "$mp")"
    local sha; sha="$(marketplace_sha "$name")"
    sha_map+="${name}=${sha}"$'\n'
  done

  SHA_MAP="$sha_map" SETTINGS="$SETTINGS_JSON" python3 - "$list_json" <<'PY'
import json, os, sys

plugins = json.loads(sys.argv[1])
settings = json.load(open(os.environ["SETTINGS"]))
enabled_cfg = {k for k, v in settings.get("enabledPlugins", {}).items() if v}

sha_map = {}
for line in os.environ.get("SHA_MAP", "").splitlines():
    if "=" in line:
        name, sha = line.split("=", 1)
        sha_map[name] = sha

out = {}
for p in plugins:
    pid = p.get("id", "")
    if pid not in enabled_cfg:            # only track plugins enabled in settings.json
        continue
    if p.get("scope") != "user" or not p.get("enabled"):
        continue
    marketplace = pid.split("@", 1)[1] if "@" in pid else ""
    sha = sha_map.get(marketplace, "")
    out[pid] = {
        "version": p.get("version", "unknown"),
        "marketplace": marketplace,
        "marketplaceType": "git" if sha else "gcs",
        "gitCommitSha": sha,
        "scope": "user",
    }

doc = {
    "_note": "Generated by claude-plugins.sh gen-lock. Do not hand-edit; run 'dot plugins update'.",
    "plugins": dict(sorted(out.items())),
}
print(json.dumps(doc, indent=2))
PY
}

cmd_gen_lock() {
  mkdir -p "$(dirname "$LOCKFILE")"
  gen_lock > "${LOCKFILE}.tmp" || die "lockfile generation failed"
  mv "${LOCKFILE}.tmp" "$LOCKFILE"
  ok "Lockfile written: ${LOCKFILE#"$DOTFILES_ROOT"/}"
}

# --- patch application (strict, fail-loud) -----------------------------------
# Resolve a plugin's install root from 'claude plugin list --json'.
plugin_install_root() {
  local plugin_id="$1"
  local list_json; list_json="$("$(claude_bin)" plugin list --json 2>/dev/null)" || return 0
  python3 -c '
import json, sys
pid = sys.argv[2]
for p in json.loads(sys.argv[1]):
    if p.get("id") == pid and p.get("scope") == "user" and p.get("enabled"):
        print(p.get("installPath", "")); break
' "$list_json" "$plugin_id"
}

# Apply every patch under PATCHES_DIR/<plugin>/*.patch to its plugin install root.
# git apply --check first; already-applied is detected and skipped; conflicts fail loud.
apply_patches() {
  local any=0
  local plugin_dir
  for plugin_dir in "${PATCHES_DIR}"/*/; do
    [ -d "$plugin_dir" ] || continue
    local plugin; plugin="$(basename "$plugin_dir")"
    # patch filenames are <version>-<slug>.patch; find the plugin's enabled id.
    local plugin_id; plugin_id="$(lock_plugin_id_for "$plugin")"
    [ -n "$plugin_id" ] || { warn "no enabled plugin matches patch dir '$plugin' — skipping"; continue; }
    local root; root="$(plugin_install_root "$plugin_id")"
    [ -n "$root" ] && [ -d "$root" ] || die "install root for '$plugin_id' not found — cannot apply patches"
    local patch
    for patch in "$plugin_dir"*.patch; do
      [ -e "$patch" ] || continue
      any=1
      if git apply --directory="$root" --unsafe-paths --check "$patch" >/dev/null 2>&1; then
        git apply --directory="$root" --unsafe-paths "$patch" \
          || die "patch failed to apply after passing --check: ${patch#"$DOTFILES_ROOT"/}"
        ok "applied ${patch#"$DOTFILES_ROOT"/}"
      elif git apply --directory="$root" --unsafe-paths --reverse --check "$patch" >/dev/null 2>&1; then
        info "already applied: ${patch#"$DOTFILES_ROOT"/}"
      else
        die "patch does NOT apply cleanly (upstream file changed?): ${patch#"$DOTFILES_ROOT"/}
     Re-derive it against the current pinned version, then retry."
      fi
    done
  done
  [ "$any" -eq 1 ] || info "no patches to apply"
}

# Map a patch directory name (plugin short name) to its enabled plugin id via the lock.
lock_plugin_id_for() {
  local short="$1"
  [ -f "$LOCKFILE" ] || { echo ""; return; }
  python3 - "$short" "$LOCKFILE" <<'PY'
import json, sys
short, lock = sys.argv[1], sys.argv[2]
data = json.load(open(lock)).get("plugins", {})
for pid in data:
    if pid.split("@", 1)[0] == short:
        print(pid); break
PY
}

# --- hooks relink (safety net; dotbot owns the canonical link) ---------------
relink_hooks() {
  local target="${CLAUDE_HOME}/hooks"
  if [ -L "$target" ] && [ "$(readlink "$target")" = "$HOOKS_SRC" ]; then
    return 0
  fi
  if [ -e "$target" ] && [ ! -L "$target" ]; then
    warn "\$HOME/.claude/hooks exists and is not the expected symlink — leaving as-is (dotbot manages it)"
    return 0
  fi
  ln -sfn "$HOOKS_SRC" "$target"
  ok "linked ~/.claude/hooks -> ${HOOKS_SRC#"$DOTFILES_ROOT"/}"
}

# --- subcommands -------------------------------------------------------------
cmd_status() {
  [ -f "$LOCKFILE" ] || die "no lockfile at ${LOCKFILE#"$DOTFILES_ROOT"/} — run 'dot plugins gen-lock' or 'dot plugins restore'"
  local current; current="$(gen_lock)"
  # Compare current machine state against committed lock; report per-plugin.
  local drift=0
  if ! diff <(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1]))["plugins"],sort_keys=True,indent=2))' "$LOCKFILE") \
            <(echo "$current" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["plugins"],sort_keys=True,indent=2))') \
       >/dev/null 2>&1; then
    warn "version drift between installed plugins and lockfile:"
    diff <(python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1]))["plugins"],sort_keys=True,indent=2))' "$LOCKFILE") \
         <(echo "$current" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["plugins"],sort_keys=True,indent=2))') \
      || true
    drift=1
  else
    ok "installed plugins match lockfile"
  fi
  # Patch state: is each tracked patch currently applied?
  local plugin_dir
  for plugin_dir in "${PATCHES_DIR}"/*/; do
    [ -d "$plugin_dir" ] || continue
    local plugin; plugin="$(basename "$plugin_dir")"
    local plugin_id; plugin_id="$(lock_plugin_id_for "$plugin")"
    [ -n "$plugin_id" ] || continue
    local root; root="$(plugin_install_root "$plugin_id")"
    local patch
    for patch in "$plugin_dir"*.patch; do
      [ -e "$patch" ] || continue
      local rel="${patch#"$DOTFILES_ROOT"/}"
      if [ -z "$root" ] || [ ! -d "$root" ]; then
        warn "patch ${rel}: plugin not installed"; drift=1; continue
      fi
      if git apply --directory="$root" --unsafe-paths --reverse --check "$patch" >/dev/null 2>&1; then
        ok "patch applied: ${rel}"
      elif git apply --directory="$root" --unsafe-paths --check "$patch" >/dev/null 2>&1; then
        warn "patch NOT applied: ${rel}"; drift=1
      else
        warn "patch would FAIL (upstream changed): ${rel}"; drift=1
      fi
    done
  done
  [ "$drift" -eq 0 ] || exit 1
}

cmd_update() {
  info "Updating marketplaces…"
  "$(claude_bin)" plugin marketplace update >/dev/null 2>&1 || warn "marketplace update reported an issue (continuing)"
  info "Updating enabled plugins to latest…"
  local pid
  while IFS= read -r pid; do
    [ -n "$pid" ] || continue
    info "  update ${pid}"
    "$(claude_bin)" plugin update "$pid" >/dev/null 2>&1 || warn "  update failed for ${pid} (continuing)"
  done < <(python3 -c 'import json,sys; print("\n".join(json.load(open(sys.argv[1]))["plugins"].keys()))' "$LOCKFILE" 2>/dev/null || true)
  info "Regenerating lockfile…"
  cmd_gen_lock
  info "Reapplying patches…"
  apply_patches
  relink_hooks
  echo
  info "Review and commit these changes:"
  git -C "$DOTFILES_ROOT" --no-pager diff --stat -- apps/claude/plugins/plugins.lock.json apps/claude/patches || true
}

cmd_restore() {
  [ -f "$LOCKFILE" ] || die "no lockfile at ${LOCKFILE#"$DOTFILES_ROOT"/} — nothing to restore"
  info "Restoring pinned plugins from lockfile…"
  # Iterate lock entries: git-backed -> checkout sha then install; gcs -> install + assert.
  while IFS=$'\t' read -r pid version mtype sha; do
    [ -n "$pid" ] || continue
    local marketplace="${pid##*@}"
    if [ "$mtype" = "git" ] && [ -n "$sha" ]; then
      if marketplace_is_git "$marketplace"; then
        git -C "${MARKETPLACES_DIR}/${marketplace}" checkout --quiet "$sha" 2>/dev/null \
          || warn "could not checkout ${marketplace}@${sha:0:8} (already at it, or fetch needed)"
      fi
    fi
    info "  install ${pid}"
    "$(claude_bin)" plugin install "$pid" --scope user >/dev/null 2>&1 \
      || warn "  install reported an issue for ${pid}"
    # Drift-assert for gcs (and any pinned) plugins with a concrete version.
    if [ "$version" != "unknown" ]; then
      local list_json; list_json="$("$(claude_bin)" plugin list --json 2>/dev/null)"
      local got; got="$(python3 -c '
import json,sys
pid=sys.argv[2]
for p in json.loads(sys.argv[1]):
    if p.get("id")==pid and p.get("scope")=="user":
        print(p.get("version","")); break
' "$list_json" "$pid")"
      if [ -n "$got" ] && [ "$got" != "$version" ]; then
        die "version drift for ${pid}: locked ${version}, installed ${got}.
     The GCS marketplace has moved past the pin and old versions can't be reinstalled.
     Run 'dot plugins update' to accept ${got} and refresh any patches, or pin a git-backed source."
      fi
    fi
  done < <(python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))["plugins"]
for pid,meta in d.items():
    print("\t".join([pid, meta.get("version","unknown"), meta.get("marketplaceType","gcs"), meta.get("gitCommitSha","")]))
' "$LOCKFILE")
  info "Applying patches…"
  apply_patches
  relink_hooks
  ok "restore complete"
}

usage() {
  cat >&2 <<EOF
Usage: dot plugins <command>

  status     Report drift + patch state (exit non-zero on drift; CI-friendly)
  update     Update to latest, regenerate lock, reapply patches, show diff
  restore    Rebuild pinned state from the lockfile (install-then-patch)
  gen-lock   Regenerate the lockfile from current machine state
EOF
  exit 2
}

main() {
  local cmd="${1:-}"; shift || true
  case "$cmd" in
    status)   cmd_status "$@" ;;
    update)   cmd_update "$@" ;;
    restore)  cmd_restore "$@" ;;
    gen-lock) cmd_gen_lock "$@" ;;
    ""|-h|--help|help) usage ;;
    *) warn "unknown command: ${cmd}"; usage ;;
  esac
}

main "$@"
